# fly.toml app configuration file generated for fly-io-s0beea on 2025-10-20T00:53:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-io-s0beea'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
